import 'package:freezed_annotation/freezed_annotation.dart';

part 'failures.freezed.dart';

/// A sealed set of typed failures returned from repositories as the left side
/// of `Either<Failure, T>`. Presentation maps these to localized copy.
@freezed
sealed class Failure with _$Failure {
  const Failure._();

  const factory Failure.server({required String message}) = ServerFailure;
  const factory Failure.cache({required String message}) = CacheFailure;
  const factory Failure.network({required String message}) = NetworkFailure;
  const factory Failure.validation({required String message, String? code}) =
      ValidationFailure;
  const factory Failure.unauthorized({required String message}) =
      UnauthorizedFailure;
  const factory Failure.unexpected({required String message}) =
      UnexpectedFailure;

  /// Stable key so the UI can look up a localized string. The raw [message]
  /// getter is generated by freezed (shared across all variants).
  String get l10nKey => switch (this) {
        ServerFailure() => 'serverError',
        CacheFailure() => 'cacheError',
        NetworkFailure() => 'noConnection',
        ValidationFailure(:final code) => switch (code) {
            'invalid_credentials' => 'invalidCredentials',
            'conflict' => 'emailTaken',
            'invalid_code' => 'invalidOtp',
            'wrong_password' => 'wrongPassword',
            _ => 'somethingWentWrong',
          },
        UnauthorizedFailure() => 'pleaseLogin',
        UnexpectedFailure() => 'unexpectedError',
      };
}
